name: "Hello Actions"
description: "Greet someone"
author: "hendrik@alterra.id"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  MY_JOB:
    description: "My Job"
    required: true
    default: "Software Engineer"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
